CREATE TABLE [dbo].[Questions] (
    [Id]                   INT            IDENTITY (1, 1) NOT NULL,
    [TenantId]             NVARCHAR (MAX) NULL,
    [GroupId]              NVARCHAR (MAX) NULL,
    [TeamId]               NVARCHAR (MAX) NULL,
    [TeamName]             NVARCHAR (MAX) NULL,
    [ConversationId]       NVARCHAR (MAX) NULL,
    [MessageId]            NVARCHAR (MAX) NULL,
    [Topic]                NVARCHAR (100) NULL,
    [Status]               NVARCHAR (50)  NULL,
    [QuestionText]         NVARCHAR (MAX) NULL,
    [OriginalPosterId]     INT            NOT NULL,
    [DateSubmitted]        DATETIME       NOT NULL,
    [Link]                 NVARCHAR (MAX) NULL,
    [AnswerText]           NVARCHAR (MAX) NULL,
    [AnswerMessageId]      NVARCHAR (MAX) NULL,
    [AnswerPosterId]       INT            NULL,
    [DateAnswered]         DATETIME       NULL,
    [QRQuestionID]         INT            NULL,
    [AnswerCardActivityId] NVARCHAR (MAX) NULL,
    [CourseID]             INT            NULL,
    CONSTRAINT [PK_Questions] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [FK_Questions_Users] FOREIGN KEY ([OriginalPosterId]) REFERENCES [dbo].[Users] ([Id]),
    CONSTRAINT [FK_Questions_Users1] FOREIGN KEY ([AnswerPosterId]) REFERENCES [dbo].[Users] ([Id])
);

