//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.QBot.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QBotEntities : DbContext
    {
        public QBotEntities()
            : base("name=QBotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Question> Questions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<TutorialGroup> TutorialGroups { get; set; }
        public virtual DbSet<TutorialGroupMembership> TutorialGroupMemberships { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserCourseRoleMapping> UserCourseRoleMappings { get; set; }
    }
}
