//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Teams.Apps.QBot.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TutorialGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TutorialGroup()
        {
            this.TutorialGroupMemberships = new HashSet<TutorialGroupMembership>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
    
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TutorialGroupMembership> TutorialGroupMemberships { get; set; }
    }
}
